# Generated by Django 2.0.1 on 2018-02-17 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('activitysheet', '0001_initial'), ('activitysheet', '0002_dailyactivitysheet'), ('activitysheet', '0003_activity'), ('activitysheet', '0004_auto_20180207_2231'), ('activitysheet', '0005_auto_20180210_0928')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DailyActivitySheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitysheet.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('activitysheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitysheet.DailyActivitySheet')),
            ],
        ),
        migrations.RemoveField(
            model_name='dailyactivitysheet',
            name='person',
        ),
        migrations.AddField(
            model_name='dailyactivitysheet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
