# Generated by Django 2.0.1 on 2018-02-01 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitysheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivitySheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitysheet.Person')),
            ],
        ),
    ]
