# Generated by Django 2.0.2 on 2018-02-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitysheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitysheet',
            name='total_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='activitysheet',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
