# Generated by Django 2.0.1 on 2018-02-01 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitysheet', '0002_dailyactivitysheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('activitysheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activitysheet.DailyActivitySheet')),
            ],
        ),
    ]
